Milestone4
Ashah15/React-app pull request #3
Opened 2021-04-16 17:06 UTC by Ashah15

Created the logic folder and initialize the calculate.js and operate.js file. Implemented the two files module and added the big.js dependancy.

2021-04-17 01:30 UTC, uryelah requested changes
Hi **Asha** , I'm Sarah your reviewer for this PR 👩‍🚀 

Goof job starting out this milestone! There are still logic issues to fix in the code so please make sure to test the calculate method yourself with console logs, compare it with the behavior of a real calculator, and then read my requests and make the necessary modifications.

Don't get discouraged though, you've done most of the job, just go on for a little more.

Read the points I mention below, work on the fixes, and submit for a new review.

Keep on coding and Rock on! 🎸 👨‍🎤 

# Require Changes ♻️ 

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-04-17 01:30 UTC, uryelah commented on src/logic/calculate.js
> +  }
- [ ] Please make sure that all possible cases are covered.
  - There are buttons without a conditional case, for example "+"
- [ ] What if there's only a single number entered? Make sure that value passes from next to total.
- [ ] Test your logic with console logs, passing mock objects to calculate, in order to debug the logic and make sure it works as a normal calculator for all the operations.
Ex:
```javaScript
console.log(calculate({total: 1, next: 4, operation: '+'}));
// what is the result of this? In theory it should be {total: 5, next: null, operation: null }
//what is your code returning instead?
```

2021-04-17 01:30 UTC, uryelah commented on src/logic/operate.js
> +  } else if (operation === '%') {
- [ ] The modifier button should turn the number into a percentage based number, e.g. 95 % == .95

2021-04-23 04:46 UTC, mahmoud717 requested changes
### Status: Invalid ❌ ❌ 

**Hello @Ashah15** 

### this pull request is marked as invalid for the following reasons
---

- [ ] Please fix all the linters issues before requesting another code review.
- [ ] you can fix the issue by returning a value directly inside the calculate (not wrapped in an if/else statement). 

---

please make these changes and request another code review

2021-04-24 13:45 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @Ashah15**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-04-26 16:25 UTC, merged