Milestone5
Ashah15/React-app pull request #4
Opened 2021-04-30 21:42 UTC by Ashah15

Tying the calculations module with the components and adding the interaction to the buttons.

2021-05-07 15:42 UTC, uche-inyama requested changes
## Changes Required

### Hi Ashah15 :slightly_smiling_face: 

Looking through the components you have updated, everything seems to be done properly. However, after installing and running your application locally on my machine; the buttons were unresponsive when I clicked on them. I will leave a gif below for reference. Also, on the console there is an error about a prop **wide**. I will also leave a snapshot for reference.

![errorCalc](https://user-images.githubusercontent.com/46329537/117474282-b0018200-af52-11eb-97ff-0253b3789ca2.gif)
![consoleError](https://user-images.githubusercontent.com/46329537/117474308-b68ff980-af52-11eb-9a05-9d2aa0c91414.png)


#### Please look into these errors, then submit another form for a code review.


### Happy coding :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

2021-05-22 12:57 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @Ashah15, a great effort :+1: However, none of the comments from the previous review was addressed. Kindly fix the comments and submit another code review request :+1: 

- Errors in our browser console as in the screenshot below
![bb](https://user-images.githubusercontent.com/46388113/119227403-2da1c200-bafd-11eb-8288-8e13c4171169.png)
- When a user clicks on any of the buttons, there is a "clickhandler" is not a function error. Kindly fix it

Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-09-06 20:22 UTC, rukundoeric requested changes
Hi @Ashah15, 

_Great job so far 👏 💯 👍. You've done well implementing some of the requested changes. However, there are still some which aren't addressed yet. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 
  - Addressed some of the issues raised from the previous review. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
  
  - N/A 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-09-06 20:22 UTC, rukundoeric commented on src/components/Button.js
> +/* eslint-disable react/default-props-match-prop-types */
- [ ] <b>REQUIRED:</b> You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.

2021-09-06 20:22 UTC, rukundoeric commented on src/components/CalcLayout.js
> +// export default CalcLayout;
- [ ] <b>REQUIRED:</b> This file is useless, kindly remove it.

2021-09-06 20:22 UTC, rukundoeric commented on src/logic/calculate.js
> +/* eslint-disable no-restricted-globals */
- [ ] <b>REQUIRED:</b> You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.

2021-09-06 20:44 UTC, rukundoeric approved these changes
Hi @Ashah15,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------

2021-09-06 20:45 UTC, merged