Tests
Ashah15/React-app pull request #5
Opened 2021-10-26 15:20 UTC by Ashah15

Add tests to the calculate,js file so as to test the functionality of the project

2021-10-27 14:49 UTC, rukundoeric requested changes
Hi @Ashah15, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] All of your tests are failing, Kindly fix them.
       ![Screen Shot 2021-10-27 at 16 43 35](https://user-images.githubusercontent.com/45217364/139089884-4391ee39-b035-437b-a9ac-3ed60677325d.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-11-03 19:24 UTC, afanimartin requested changes
Hi @Ashah15, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] please fix the failing tests. you still have 24 failing cases.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

### Martin Afani
#### Slack: whiz25

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 08:17 UTC, e71az requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hi, @Ashah15, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] Please upgrade your snapshot files in order to make your tests pass, after doing this everything will pass as expected:

![image](https://user-images.githubusercontent.com/38522578/140279942-727a66e5-e189-4876-9ce9-2c69b810930a.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 11:02 UTC, e71az requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hi, @Ashah15, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] In the last commit that you did I could only observe that you deleted the snapshot file but no updates were made, your tests are still displaying differences because of this, the only thing that you have to do is to run npm test and then press U to update your snapshots, after that, pushing should be the only thing remaining to do, please do so to comply with the project requirements 👍 

![image](https://user-images.githubusercontent.com/38522578/140302880-12f5e68c-4f88-43ff-828f-5efbc9250a01.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 13:53 UTC, addod19 requested changes
### Hi @Ashah15, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 13:53 UTC, addod19 commented on src/logic/calculate.test.js
> +});
- [ ] It would be better if we fix the ESLint error, we can do it by adding another line to the file or run `npx eslint .`

2021-11-04 13:53 UTC, addod19 commented on src/logic/calculate.test.js
> +    expect(calculate({ result: '21', next: '3', operation: '+' }, '=')).toStrictEqual({ next: null, operation: null, result: '24' });
- [ ] It would be better if we test more functionality of the application. In this case, we only have a test for the `addition` operation

2021-11-04 13:53 UTC, addod19 commented on src/logic/calculate.test.js
> +  });
- [ ] It would be better if we fix the failing test as pointed out earlier

2021-11-11 23:40 UTC, e71az requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hi, @Ashah15, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] You are only missing to update one snapshot to be done with this project, please after running your tests press u to update the snapshots and then make sure that you are pushing the new snapshots to your project repo in order for us to see the correct testing output:

![image](https://user-images.githubusercontent.com/38522578/141384191-ed700968-31f7-472e-a400-f46bc0f5931c.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 12:11 UTC, rukundoeric approved these changes
Hi @Ashah15,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------

2021-11-22 08:49 UTC, merged